site_name: UbuCon Asia Documentations
site_name_short: UbuCon Asia Docs
site_url: http://www.ubucon.asia
site_base_url: /
site_description: General and detailed documentation and guidance on UbuCon Asia
site_author: UbuCon Asia Committee

repo_url: https://github.com/ubucon-asia/docs.ubucon.asia
repo_name: ubucon-asia/docs.ubucon.asia
contact_email: contact@ubuntu.com
copyright: Copyright &copy; 2023-Present UbuCon Asia Committee (contact at ubucon.asia)
copyright_details: Ubuntu and Canonical are registered trademarks of Canonical Ltd.
edit_uri: /blob/main/docs

theme:
    name: ubuntu

nav:
    - Home:
      - index.md
      - general/chat.md
    - Organizer:
      - organizer/index.md
      - organizer/overview.md
      - organizer/teams_roles.md

plugins:
    - search
